banking_project/banking_app/urls.py
from django.urls import path,include
from . import views
app_name = 'banking_app'
urlpatterns = [
    path('', views.home,name='home'),
    path('register/',views.register,name='register'),
    path('login/',views.login, name='login'),
    # path('<slug:dist_slug>/', views.allDistricts,name='branches_by_districts'),
    # path('<slug:dist_slug>/<slug:branch_slug>/', views.branchDistrictDetail,name='branchDistrictDetail'),
    path('details/',views.details,name='details'),
]

banking_project/banking_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('banking_app.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

banking_project/banking_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Material(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class District(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'district'
        verbose_name_plural = 'districts'

    def get_url(self):
        return reverse('banking_app:branches_by_districts',args=[self.slug])

    def __str__(self):
        return self.name

class Branch(models.Model):
    name = models.CharField(max_length=250)
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)

    def get_url(self):
        return reverse('banking_app:branchDistrictDetail', args=[self.District.slug, self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'branch'
        verbose_name_plural = 'branches'

    def __str__(self):
        return self.name

class Details(models.Model):
    GENDER_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
    ]
    ACCOUNT_CHOICES =[
        ('savings', 'savings'),
        ('current', 'current'),
    ]
    name = models.CharField(max_length=250, null=False)
    dob = models.DateField()
    age = models.IntegerField()
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    phone_number = models.CharField(max_length=15)
    mail_id = models.EmailField(max_length=100)
    address = models.TextField(max_length=350)
    district = models.ForeignKey(District,on_delete=models.CASCADE)
    branch = models.ForeignKey(Branch,on_delete=models.CASCADE)
    account = models.CharField(max_length=10, choices=ACCOUNT_CHOICES)
    materials_provide = models.ManyToManyField(Material)
    def __str__(self):
        return self.name

banking_project/banking_app/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .models import Details,District,Branch,Material

# Create your views here.
def home(request):
    return render(request,'index.html')

def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        password1 = request.POST['password1']
        if password == password1:
            if User.objects.filter(username=username).exists():
                messages.info(request,"username taken")
                return redirect('banking_app:register')

            else:
                user = User.objects.create_user(username=username, password=password)
                user.save()
                print("user created")
                return redirect('banking_app:login')
        else:
            print("password mismatch")
            return redirect('banking_app:register')
        return redirect('/')
    return render(request,'register.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,"invalid credentials")
            return redirect('login')
    return render(request,'login.html')

def details(request):
    districts = District.objects.all()
    branchess = Branch.objects.all()

    if request.method == 'POST':
        name = request.POST['name']
        dob = request.POST['dob']
        age = request.POST['age']
        gender = request.POST['gender']
        phone_number = request.POST['phone_number']
        mail_id = request.POST['mail_id']
        address = request.POST['address']
        district_id = request.POST['district']
        branchess = Branch.objects.filter(district_id=district_id)

        branch_id = request.POST.get('branch')
        account = request.POST['account']
        materials_provide = request.POST.getlist('materials_provide')


        detail_dist = Details(
            name=name,
            dob=dob,
            age=age,
            gender=gender,
            phone_number=phone_number,
            mail_id=mail_id,
            address=address,
            district_id=district_id,
            branch_id=branch_id,
            account=account,
        )


        detail_dist.save()


        material_objects = Material.objects.filter(name__in=materials_provide)
        detail_dist.materials_provide.set(material_objects)


        messages.info(request, "Application accepted")

    return render(request, 'details.html', {'districts': districts, 'branchess': branchess})




# def allDistricts(request):
#     # if dist_slug != None:
#     #     c_page = get_object_or_404(Category, slug=c_slug)
#     #     products_list=Product.objects.all().filter(category=c_page,available=True)
#     # else:
#     #     products_list=Product.objects.all().filter(available=True)
#
#     # ,{'category': c_page, 'products': products}
#     return render(request,'Details.html')
#
#
# def branchDistrictDetail(request):
#     # try:
#     #     product = Product.objects.get(category__slug=c_slug,slug=product_slug)
#     # except Exception as e:
#     #     raise e
#     # , {'product': product}
#     return render(request,'Details.html')
#

banking_project/templates/about.html
{% load static %}
<div class="site-section cta-big-image" id="about-section">
  <div class="container">
    <div class="row mb-5 justify-content-center">
      <div class="col-md-8 text-center">
        <h2 class="section-title mb-3" data-aos="fade-up" data-aos-delay="">About Us</h2>
        <p class="lead" data-aos="fade-up" data-aos-delay="100">Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus minima neque tempora reiciendis.</p>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6 mb-5" data-aos="fade-up" data-aos-delay="">
        <figure class="circle-bg">
          <img src="{% static 'images/hero_1.jpg' %}" alt="Free Website Template by Free-Template.co" class="img-fluid">
        </figure>
      </div>

      <div class="col-lg-5 ml-auto" data-aos="fade-up" data-aos-delay="100">
        <h3 class="text-black mb-4">We Solve Your Financial Problem</h3>
        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
        <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
      </div>
    </div>
  </div>
</div>

banking_project/templates/base.html
{% load static %}
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
    <div id="overlayer"></div>
      <div class="loader">
        <div class="spinner-border text-primary" role="status">
          <span class="sr-only">Loading...</span>
        </div>
      </div>
      <div class="site-wrap">
        <div class="site-mobile-menu site-navbar-target">
          <div class="site-mobile-menu-header">
            <div class="site-mobile-menu-close mt-3">
              <span class="icon-close2 js-menu-toggle"></span>
            </div>
          </div>
          <div class="site-mobile-menu-body">
          </div>
        </div>

        <header class="site-navbar js-sticky-header site-navbar-target" role="banner">
          <div class="container">
            <div class="row align-items-center">
              <div class="col-6 col-xl-2">
                <h1 class="mb-0 site-logo"><a href="index.html" class="h2 mb-0">Banker<span class="text-primary">.</span> </a></h1>
              </div>
              <div class="col-12 col-md-10 d-none d-xl-block">

                {% include 'navbar.html' %}

              </div>
              <div class="col-6 d-inline-block d-xl-none ml-md-0 py-3" style="position: relative; top: 3px;"><a href="#" class="site-menu-toggle js-menu-toggle float-right"><span class="icon-menu h3"></span></a>
              </div>
            </div>
          </div>
        </header>

        <div class="site-blocks-cover overlay" style="background-image: url({% static 'images/hero_2.jpg' %});" data-aos="fade" id="home-section">
          {% block content %}
          {% endblock %}
            <a href="#next" class="mouse smoothscroll">
              <span class="mouse-icon">
                <span class="mouse-wheel"></span>
              </span>
            </a>
        </div>

    <div class="site-section" id="next">
      <div class="container">
        <div class="row mb-5">

          <div class="col-md-4 text-center" data-aos="fade-up" data-aos-delay="">
            <img src="{% static 'images/flaticon-svg/svg/001-wallet.svg' %}" alt="Free Website Template by Free-Template.co" class="img-fluid w-25 mb-4">
            <h3 class="card-title">Money Savings</h3>
            <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
          </div>

          <div class="col-md-4 text-center" data-aos="fade-up" data-aos-delay="100">
            <img src="{% static 'images/flaticon-svg/svg/004-cart.svg' %}" alt="Free Website Template by Free-Template.co" class="img-fluid w-25 mb-4">
            <h3 class="card-title">Online Shoppings</h3>
            <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
          </div>

          <div class="col-md-4 text-center" data-aos="fade-up" data-aos-delay="200">
            <img src="{% static 'images/flaticon-svg/svg/006-credit-card.svg' %}" alt="Free Website Template by Free-Template.co" class="img-fluid w-25 mb-4">
            <h3 class="card-title">Credit / Debit Cards</h3>
            <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-6 mb-5" data-aos="fade-up" data-aos-delay="">
            <figure class="circle-bg">
              <img src="{% static 'images/about_2.jpg' %}" alt="Free Website Template by Free-Template.co" class="img-fluid">
            </figure>
          </div>

          <div class="col-lg-5 ml-auto" data-aos="fade-up" data-aos-delay="100">
            <div class="mb-4">
              <h3 class="h3 mb-4 text-black">Amortization Computation</h3>
              <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
            </div>

            <div class="mb-4">
              <ul class="list-unstyled ul-check success">
                <li>Officia quaerat eaque neque</li>
                <li>Lorem ipsum dolor sit amet</li>
                <li>Consectetur adipisicing elit</li>
              </ul>
            </div>

            <div class="mb-4">
              <form action="#">
                <div class="form-group d-flex align-items-center">
                  <input type="text" class="form-control mr-2" placeholder="Enter your email">
                  <input type="submit" class="btn btn-primary" value="Submit Email">
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>

        {% include 'about.html' %}
        {% include 'team.html' %}
        {% include 'gallery.html' %}
        {% include 'working.html' %}
        {% include 'services.html' %}
        {% include 'customers.html' %}
        {% include 'pricing.html' %}
        {% include 'faq.html' %}
        {% include 'contact.html' %}
        {% include 'footer.html' %}

  </div> <!-- .site-wrap -->

  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
  <script src="{% static 'js/jquery.sticky.js' %}"></script>
  <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>


  <script src="{% static 'js/main.js' %}"></script>


  </body>
</html>

banking_project/templates/contact.html
<section class="site-section bg-light" id="contact-section" data-aos="fade">
      <div class="container">
        <div class="row mb-5">
          <div class="col-12 text-center">
            <h2 class="section-title mb-3">Contact Us</h2>
          </div>
        </div>
        <div class="row mb-5">
          <div class="col-md-4 text-center">
            <p class="mb-4">
              <span class="icon-room d-block h2 text-primary"></span>
              <span>203 Fake St. Mountain View, San Francisco, California, USA</span>
            </p>
          </div>
          <div class="col-md-4 text-center">
            <p class="mb-4">
              <span class="icon-phone d-block h2 text-primary"></span>
              <a href="#">+1 232 3235 324</a>
            </p>
          </div>
          <div class="col-md-4 text-center">
            <p class="mb-0">
              <span class="icon-mail_outline d-block h2 text-primary"></span>
              <a href="#">youremail@domain.com</a>
            </p>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12 mb-5">
            <form action="#" class="p-5 bg-white">
              <h2 class="h4 text-black mb-5">Contact Form</h2>
              <div class="row form-group">
                <div class="col-md-6 mb-3 mb-md-0">
                  <label class="text-black" for="fname">First Name</label>
                  <input type="text" id="fname" class="form-control">
                </div>
                <div class="col-md-6">
                  <label class="text-black" for="lname">Last Name</label>
                  <input type="text" id="lname" class="form-control">
                </div>
              </div>
              <div class="row form-group">
                <div class="col-md-12">
                  <label class="text-black" for="email">Email</label>
                  <input type="email" id="email" class="form-control">
                </div>
              </div>
              <div class="row form-group">
                <div class="col-md-12">
                  <label class="text-black" for="subject">Subject</label>
                  <input type="subject" id="subject" class="form-control">
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12">
                  <label class="text-black" for="message">Message</label>
                  <textarea name="message" id="message" cols="30" rows="7" class="form-control" placeholder="Write your notes or questions here..."></textarea>
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12">
                  <input type="submit" value="Send Message" class="btn btn-primary btn-md text-white">
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
</section>

banking_project/templates/customers.html
{% load static %}

<section class="site-section testimonial-wrap" id="testimonials-section" data-aos="fade">
      <div class="container">
        <div class="row mb-5">
          <div class="col-12 text-center">
            <h2 class="section-title mb-3">Happy Customers</h2>
          </div>
        </div>
      </div>
      <div class="slide-one-item home-slider owl-carousel">
          <div>
            <div class="testimonial">

              <blockquote class="mb-5">
                <p>&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;</p>
              </blockquote>

              <figure class="mb-4 d-flex align-items-center justify-content-center">
                <div><img src="{% static 'images/person_3.jpg' %}" alt="Image" class="w-50 img-fluid mb-3"></div>
                <p>John Smith</p>
              </figure>
            </div>
          </div>
          <div>
            <div class="testimonial">

              <blockquote class="mb-5">
                <p>&ldquo;A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.&rdquo;</p>
              </blockquote>
              <figure class="mb-4 d-flex align-items-center justify-content-center">
                <div><img src="{% static 'images/person_2.jpg' %}" alt="Image" class="w-50 img-fluid mb-3"></div>
                <p>Christine Aguilar</p>
              </figure>

            </div>
          </div>

          <div>
            <div class="testimonial">

              <blockquote class="mb-5">
                <p>&ldquo;Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.&rdquo;</p>
              </blockquote>
              <figure class="mb-4 d-flex align-items-center justify-content-center">
                <div><img src="{% static 'images/person_4.jpg' %}" alt="Image" class="w-50 img-fluid mb-3"></div>
                <p>Robert Spears</p>
              </figure>


            </div>
          </div>

          <div>
            <div class="testimonial">
              <blockquote class="mb-5">
                <p>&ldquo;The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen. She packed her seven versalia, put her initial into the belt and made herself on the way.&rdquo;</p>
              </blockquote>
              <figure class="mb-4 d-flex align-items-center justify-content-center">
                <div>
                  <img src="{% static 'images/person_4.jpg' %}" alt="Image" class="w-50 img-fluid mb-3">
                </div>
                <p>Bruce Rogers</p>
              </figure>
            </div>
          </div>
      </div>
</section>

banking_project/templates/details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Banker - Register
{% endblock %}

{% block content %}
    <div class="row" style="max-height: 600px; overflow-y: auto; padding-bottom: 20px;">
        <div class="col-md-8 offset-md-2">
            <div class="mt-5 mt-lg-5">

                <form action="{% url 'banking_app:details' %}" class="p-5 bg-white" method="post">
                    {% csrf_token %}
                    <h2 class="h4 text-center text-primary mb-5">Details Form</h2>

                    <div class="form-group">
                        <label class="text-black" for="name">Name</label>
                        <input type="text" id="name" name="name" class="form-control" placeholder="Enter your name">
                    </div>


                    <div class="form-group">
                        <label class="text-black" for="dob">Date of Birth</label>
                        <input type="date" id="dob" name="dob" class="form-control" placeholder="Enter your Date of Birth">
                    </div>


                    <div class="form-group">
                        <label class="text-black" for="age">Age</label>
                        <input type="text" id="age" name="age" class="form-control" placeholder="Age">
                    </div>


                    <div class="form-group">
                        <label class="text-black" for="gender">Gender</label>
                        <select id="gender" name="gender" class="form-control">
                            <option value="Male">Male</option>
                            <option value="Female">Female</option>
                            <option value="Other">Other</option>
                        </select>
                    </div>



                    <div class="form-group">
                        <label class="text-black" for="phone_number">Phone Number</label>
                        <input type="text" id="phone_number" name="phone_number" class="form-control" placeholder="Phone Number">
                    </div>


                    <div class="form-group">
                        <label class="text-black" for="mail_id">Mail ID</label>
                        <input type="text" id="mail_id" name="mail_id" class="form-control" placeholder="Mail ID">
                    </div>


                    <div class="form-group">
                        <label class="text-black" for="address">Address</label>
                        <input type="text" id="address" name="address" class="form-control" placeholder="Address">
                    </div>


                    <div class="form-group">
                        <label class="text-black" for="district">District</label>
                        <select id="district" name="district" class="form-control">
                            {% for dist in districts %}
                                <option value="{{ dist.id }}">{{ dist.name }}</option>
                            {% endfor %}
                        </select>

                    </div>



<!--                   <div class="form-group">-->
<!--                        <label class="text-black" for="branch">Branch</label>-->
<!--                        <select id="branch" name="branch" class="form-control">-->
<!--                            {% for branch in branches %}-->
<!--                                <option value="{{ branch.id }}">{{ branch.name }}</option>-->
<!--                            {% endfor %}-->
<!--                        </select>-->
<!--                   </div>-->

                    <div class="form-group">
                        <label class="text-black" for="branch">Branch</label>
                        <select id="branch" name="branch" class="form-control">
                            {% for brnch in branchess %}-->
                                <option value="{{ brnch.id }}">{{ brnch.name }}</option>
                            {% endfor %}
                        </select>
                    </div>


                    <div class="form-group">
                        <label class="text-black" for="account">Account Type</label>
                        <select id="account" name="account" class="form-control">
                            <option value="savings">Savings Account</option>
                            <option value="current">Current Account</option>

                        </select>
                    </div>


                    <div class="form-group">
                        <label class="text-black">Materials Provide</label>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="debitCard" name="materials_provide" value="debit_card">
                            <label class="form-check-label" for="debitCard">Debit Card</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="creditCard" name="materials_provide" value="credit_card">
                            <label class="form-check-label" for="creditCard">Credit Card</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="chequeBook" name="materials_provide" value="cheque_book">
                            <label class="form-check-label" for="chequeBook">Cheque Book</label>
                        </div>
                    </div>

                    <div class="row justify-content-center">
                        <div class="col-md-6 text-center">
                            <button type="submit" class="btn btn-primary btn-block">Submit</button>
                        </div>
                    </div>


                </form>
                <a href="{% url 'banking_app:home' %}" class="nav-link">Home</a>
            </div>
        </div>
    </div>

{% if messages %}
                <div class="alert alert-info">
                    <ul>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                </div>
{% endif %}
<a href="{% url 'banking_app:home' %}" class="nav-link">Home</a>
{% endblock %}

banking_project/templates/faq.html
{% load static %}
<section class="site-section" id="about-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 mb-5" data-aos="fade-up" data-aos-delay="">
            <figure class="circle-bg">
            <img src="{% static 'images/hero_1.jpg' %}" alt="Free Website Template by Free-Template.co" class="img-fluid">
            </figure>
          </div>

          <div class="col-lg-5 ml-auto" data-aos="fade-up" data-aos-delay="100">
            <div class="row">
              <div class="col-12 mb-4" data-aos="fade-up" data-aos-delay="">
                <div class="unit-4 d-flex">
                  <div class="unit-4-icon mr-4 mb-3"><span class="text-primary flaticon-head"></span></div>
                  <div>
                    <h3>Bank Loan</h3>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    <p class="mb-0"><a href="#">Learn More</a></p>
                  </div>
                </div>
              </div>
              <div class="col-12 mb-4" data-aos="fade-up" data-aos-delay="100">
                <div class="unit-4 d-flex">
                  <div class="unit-4-icon mr-4 mb-3"><span class="text-primary flaticon-smartphone"></span></div>
                  <div>
                    <h3>Banking Consulation </h3>
                    <p>Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
                    <p class="mb-0"><a href="#">Learn More</a></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
</section>

banking_project/templates/navbar.html
<nav class="site-navigation position-relative text-right" role="navigation">
    <ul class="site-menu main-menu js-clone-nav mr-auto d-none d-lg-block">
        <li><a href="{% url 'banking_app:home' %}" class="nav-link">Home</a></li>
        <li><a href="{% url 'banking_app:login' %}" class="nav-link">Login</a></li>
        <li><a href="{% url 'banking_app:register' %}" class="nav-link">Register</a></li>
        <li class="has-children">
            <a href="" class="nav-link">Branches</a>
            <ul class="dropdown">
                <li><a href="https://en.wikipedia.org/wiki/Thiruvananthapuram" class="nav-link">Thiruvananthapuram</a></li>
                <li><a href="https://en.wikipedia.org/wiki/Kollam" class="nav-link">Kollam</a></li>
                <li><a href="https://en.wikipedia.org/wiki/Pathanamthitta" class="nav-link">Pathanamthitta</a></li>
                <li><a href="https://en.wikipedia.org/wiki/Alappuzha" class="nav-link">Alappuzha </a></li>
                <li><a href="https://en.wikipedia.org/wiki/Kottayam" class="nav-link">Kottayam</a></li>
                <li><a href="https://en.wikipedia.org/wiki/Idukki_district" class="nav-link">Idukki</a></li>
            </ul>
        </li>

        <li class="social"><a href="#contact-section" class="nav-link"><span class="icon-facebook"></span></a></li>
        <li class="social"><a href="#contact-section" class="nav-link"><span class="icon-twitter"></span></a></li>
        <li class="social"><a href="#contact-section" class="nav-link"><span class="icon-linkedin"></span></a></li>
        {% if user.is_authenticated %}
        <h6 style="color:white"><b>{{user.username}}</i></b></h6>
        {% endif %}

    </ul>
</nav>